-- For table USERS
ALTER TABLE USERS
ADD PRIMARY KEY (U_UID);

-- For table PLAYLIST
ALTER TABLE PLAYLIST
ADD PRIMARY KEY (P_PLAYLISTID);

ALTER TABLE PLAYLIST
ADD FOREIGN KEY (P_UID) references USERS;

COMMIT WORK;

-- For table ARTIST
ALTER TABLE ARTIST
ADD PRIMARY KEY (AR_ARTISTID);

COMMIT WORK;

-- For table ALBUM
ALTER TABLE ALBUM
ADD PRIMARY KEY (A_ALBUMID);

ALTER TABLE ALBUM
ADD FOREIGN KEY (A_ARTISTID) references ARTIST;

COMMIT WORK;

-- For table SONG
ALTER TABLE SONG
ADD PRIMARY KEY (S_SONGID);

COMMIT WORK;

ALTER TABLE SONG
ADD FOREIGN KEY (S_ARTISTID) references ARTIST;

COMMIT WORK;

ALTER TABLE SONG
ADD FOREIGN KEY (S_ALBUMID) references ALBUM;

COMMIT WORK;
