CREATE TABLE SONG (
    S_SONGID INTEGER NOT NULL,
    S_ALBUMID INTEGER NOT NULL,
    S_ARTISTID INTEGER NOT NULL,
    S_TITLE VARCHAR(999),
    S_GENRE CHAR(99),
    S_DURATION TIME
);

CREATE TABLE PLAYLIST ( 
    P_PLAYLISTID INTEGER NOT NULL,
    P_UID INTEGER NOT NULL,
    P_TITLE VARCHAR(999),
    P_PRIVATE BOOLEAN NOT NULL,
    P_CREATIONDATE DATE,
    P_DURATION TIME
);

CREATE TABLE USERS (
    U_UID INTEGER NOT NULL,
    U_USERNAME VARCHAR(50) NOT NULL,
    U_EMAIL CHAR(999) NOT NULL,
    U_PASSWORD CHAR(50) NOT NULL
);

CREATE TABLE ALBUM (
    A_ALBUMID INTEGER NOT NULL,
    A_ARTISTID INTEGER NOT NULL,
    A_NUMBEROFSONGS INTEGER NOT NULL,
    A_RELEASEDATE DATE,
    A_DURATION TIME
);

CREATE TABLE ARTIST (
    AR_ARTISTID INTEGER NOT NULL,
    AR_NAME VARCHAR(99) NOT NULL,
    AR_COUNTRY VARCHAR(99) NOT NULL
);